spring:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  datasource:
    url: jdbc:postgresql://localhost:5432/lab
    username: postgres
    password: 123456
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
          time_zone: UTC
    hibernate:
      ddl-auto: update
  security:
    user:
      name: gianghx
      password: 123456
#  servlet:
#    multipart:
#      max-file-size: 10MB
#springdoc:
#  swagger-ui:
#    defaultModelsExpandDepth: -1
#server:
#  forward-headers-strategy: framework

#logging:
#  level:
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
